Repository netlify/netlify-identity-widget, pull requests merged in 2020-06, with the labels that each got.

#241 chore: add renovate.json
  renovate.json
Labels: type: chore

#261 chore(deps): update babel
  .babelrc
  .eslintrc.json
  package.json
  webpack.config.babel.js
  yarn.lock
Labels: type: chore

#238 feat: add multilingual support
  .eslintrc.json
  README.md
  package.json
  src/components/app.js
  src/components/controls.js
  src/components/forms/logout.js
  src/components/forms/message.js
  src/components/forms/providers.js
  src/components/forms/siteurl.js
  src/components/forms/user.js
  src/components/modal/index.js
  src/index.ejs
  src/netlify-identity.js
  src/state/store.js
  src/translations/en.json
  src/translations/fr.json
  src/translations/index.js
  src/translations/index.test.js
  yarn.lock
Labels: type: feature

#274 `yarn dev` is used to run the development server
  CONTRIBUTING.md
Labels: type: bug

#282 chore: update gotrue-js
  package.json
  yarn.lock
Labels: type: chore

#275 Indicate via @autocomplete whether a password field is for new/current values
  src/components/app.js
  src/components/forms/user.js
Labels: type: feature
