Repository netlify/netlify-identity-widget, pull requests merged in 2020-07, with the labels that each got.

#286 Changes Sign Up form type to name instead of email
  src/components/forms/user.js
Labels: type: bug

#283 feat: add support for unregistering event handlers
  README.md
  src/netlify-identity.js
  src/netlify-identity.test.js
Labels: type: feature

#284 fix: prevent double initialization
  .prettierrc.js
  src/netlify-identity.js
  src/netlify-identity.test.js
Labels: type: bug

#303 chore: remove package-lock.json
  package-lock.json
Labels: type: chore

#304 chore(deps): remove unused raw-loader dependency
  package.json
  yarn.lock
Labels: type: chore

#325 ci: switch to github actions
  .github/workflows/test.yml
  .travis.yml
Labels: type: chore

#328 Fix: Make "French" into "Français"
  src/index.ejs
Labels: type: chore

#327 Feat: Add Spanish translation
  README.md
  src/index.ejs
  src/translations/es.json
  src/translations/index.js
  src/translations/index.test.js
Labels: enhancement, type: feature

#332 Update correct dependencies
  package.json
  src/components/app.js
  src/components/controls.js
  src/components/forms/logout.js
  src/components/forms/providers.js
  src/components/forms/siteurl.js
  src/components/forms/user.js
  src/components/modal/index.js
  src/netlify-identity.js
  src/state/store.js
  yarn.lock
Labels: type: chore

#333 Feat: Update Spanish translation
  src/translations/es.json
Labels: type: feature

#319 fix: ReferenceError: window is not defined
  webpack.umd.config.babel.js
Labels: type: bug

#305 feat: Add the ability to clear an invalid site URL
  src/components/app.js
  src/components/modal/index.js
Labels: type: feature

#330 Feat: Hungarian translation
  src/index.ejs
  src/translations/hu.json
  src/translations/index.js
  src/translations/index.test.js
Labels: type: feature

#334 fix: increase input size to avoid mobile zoom
  src/components/modal.css
Labels: type: bug
